
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='imtherapy-tmb',
    version='0.0.0',
    description='Tumor mutation burden feature transformation module for imtherapy',
    python_requires='==3.*,>=3.7.0',
    author='pwwang',
    author_email='pwwang@pwwang.com',
    license='MIT',
    entry_points={"imtherapy_feature_transform": ["tmb = imtherapy_tmb:FeatureTransformTmb"]},
    packages=['imtherapy_tmb'],
    package_dir={"": "."},
    package_data={},
    install_requires=['imtherapy==0.*,>=0.0.0', 'pipen==0.*,>=0.0.2'],
)
